@startuml
actor Utilizador as u
participant "barbatos_rex1.io:IOManager" as barbatos_rex1.io
participant "firewall:FileFireWall" as firewall
participant "manager:Manager" as manager
participant "file:File" as file
participant "in:Inporter" as in
autonumber
activate u
u-->barbatos_rex1.io** : barbatos_rex1.io = create(String path)
activate barbatos_rex1.io
barbatos_rex1.io -->firewall** : firewall = create(String path)
activate firewall
firewall -->manager** : manager = create(String path)
activate manager
manager -->file** : file = File(String path)
manager --> in** : in = create(File file)
manager -> in : get()
activate in
deactivate
deactivate
deactivate
deactivate
@enduml