@startuml

actor Utilizador as u

participant ":IOManager" as barbatos_rex1.io


autonumber
activate u
u->barbatos_rex1.io**: intancia barbatos_rex1.io com o ficheiro (ou o seu caminho).
u->barbatos_rex1.io: deleteFile()
activate barbatos_rex1.io
barbatos_rex1.io --> u : Retorna o sucesso
deactivate

@enduml