@startuml
actor Utilizador as u

participant ":IOManager" as barbatos_rex1.io

autonumber
u-> barbatos_rex1.io : Executa o método de criar o ficheiro\n com o caminhocomo parâmetro
activate barbatos_rex1.io
barbatos_rex1.io --> u : O IOManager cria o ficheiro e retorna o sucesso
deactivate


@enduml